version: "3.5"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cstrike/addons:/home/steam/hlds/cstrike/addons
      - ./cstrike/logs:/home/steam/hlds/cstrike/logs
      - ./cstrike/cfgs:/home/steam/hlds/cstrike/cfgs:ro
      - ./cstrike/liblist.gam:/home/steam/hlds/cstrike/liblist.gam:ro
      - ./cstrike/mapcycle.txt:/home/steam/hlds/cstrike/mapcycle.txt:ro
      - ./cstrike/server.cfg:/home/steam/hlds/cstrike/server.cfg:ro
      - ./cstrike/motd.html:/home/steam/hlds/cstrike/motd.html:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/maps:ro
    ports:
      - "27015:27015"
      - "27015:27015/udp"
